import type { QuizQuestion } from '@/lib/types'

export const domain4Questions: QuizQuestion[] = [
  // ── System Prompts ────────────────────────────────────────────────────────
  {
    id: 'd4-q1',
    domain: 4,
    scenario: 'customer-support',
    question: 'A multi-tenant SaaS uses Claude for support. Each tenant has unique branding and config. A developer interpolates tenant config into the system prompt: `system = f"You are {tenant.name}\'s assistant. Config: {tenant.config}"`. What is the primary problem?',
    options: {
      A: 'System prompts cannot exceed 1,000 tokens',
      B: 'Interpolating dynamic tenant data into the system prompt breaks prompt caching and creates prompt injection risk',
      C: 'f-strings are not supported in API calls',
      D: 'Each tenant should have a separate Claude API key',
    },
    correct: 'B',
    explanation: {
      correct: 'Interpolating dynamic per-tenant data into the system prompt causes two problems: (1) the cached system prompt prefix is different for every tenant, preventing cache hits and eliminating cost savings; (2) malicious tenant-controlled values in the system prompt can override instructions (prompt injection). The correct pattern is to keep the system prompt static and pass tenant-specific data in the human turn or in a clearly delimited non-cached section.',
      A: 'System prompt length is bounded by the context window, not a fixed 1,000-token limit.',
      B: 'Correct — dynamic system prompt injection breaks caching and introduces injection risk.',
      C: 'f-strings are valid Python — this is an architectural issue, not a syntax one.',
      D: 'Separate API keys per tenant is operationally impractical and does not solve either issue.',
    },
    relatedTopic: '/study/domain-4/system-prompts',
  },
  {
    id: 'd4-q2',
    domain: 4,
    scenario: 'payments-api',
    question: 'A developer needs Claude to output pure JSON with no preamble. They add `"Always respond in JSON"` to the system prompt but occasionally see responses like "Here\'s the JSON: {…}". What is the most reliable fix?',
    options: {
      A: 'Change to "ALWAYS respond in JSON" (uppercase for emphasis)',
      B: 'Prefill the assistant turn with `{` so Claude continues from an open brace',
      C: 'Switch to a different Claude model',
      D: 'Add "Do not add preamble" to the system prompt',
    },
    correct: 'B',
    explanation: {
      correct: 'Prefilling the assistant turn with `{` forces Claude to continue from that character — it cannot produce preamble because the response has already started with `{`. This is the most reliable mechanism. System prompt instructions reduce but do not eliminate preamble. Uppercase emphasis and additional instructions are advisory.',
      A: 'Uppercase emphasis is advisory — it does not structurally prevent preamble.',
      B: 'Correct — prefilling `{` is a structural guarantee. Claude must complete from that open brace.',
      C: 'This is a prompting issue, not a model capability issue.',
      D: '"Do not add preamble" is still just an instruction that can be violated.',
    },
    relatedTopic: '/study/domain-4/system-prompts',
  },

  // ── Few-Shot Prompting ────────────────────────────────────────────────────
  {
    id: 'd4-q3',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A team uses 8 few-shot examples for a classification task. Despite detailed instructions, Claude\'s output format is inconsistent — sometimes with explanations, sometimes without. What is the most likely root cause?',
    options: {
      A: '8 examples is too many — reduce to 3',
      B: 'The examples themselves have inconsistent formats — Claude mirrors examples over instructions',
      C: 'Few-shot examples must be in the system prompt to take effect',
      D: 'Classification tasks require fine-tuning, not few-shot prompting',
    },
    correct: 'B',
    explanation: {
      correct: 'When examples and instructions conflict, Claude follows examples. If some examples include explanations and others do not, Claude mirrors that inconsistency. Every example must produce output in exactly the target format — not approximately. Audit examples for format consistency before adding more.',
      A: 'More or fewer examples is not the issue — consistency is.',
      B: 'Correct — examples take precedence over instructions. Every example must be format-perfect.',
      C: 'Few-shot examples go in alternating user/assistant turns, not the system prompt.',
      D: 'Few-shot prompting is one of the strongest approaches for classification.',
    },
    relatedTopic: '/study/domain-4/few-shot-prompting',
  },
  {
    id: 'd4-q4',
    domain: 4,
    scenario: 'customer-support',
    question: 'A support ticket classifier has 5 categories. 80% of tickets are "billing", 5% each for the other 4. How should few-shot examples be selected?',
    options: {
      A: '1 example per category (5 total) for balanced representation',
      B: '80% billing examples to match the real distribution',
      C: 'Cover edge cases and ambiguous inputs across all categories with slight weighting toward billing',
      D: 'Examples only for the 4 rarest categories since billing is easy',
    },
    correct: 'C',
    explanation: {
      correct: 'Few-shot examples should cover edge cases and ambiguous inputs (the hardest cases to classify) across all categories, while slightly reflecting real distribution. Purely balanced (A) undertunes for billing. Purely distribution-matching (B) underrepresents rare-category edge cases. Rare-category-only (D) confuses Claude about the distribution. Balanced coverage of ambiguous cases with distribution awareness is optimal.',
      A: 'Equal distribution undertunes for the dominant class and omits important edge cases.',
      B: '80% billing examples may not cover rare-category nuances that matter for accuracy.',
      C: 'Correct — edge case coverage across all categories with some distribution reflection.',
      D: 'Rare-category-only examples bias Claude to misclassify easy billing cases.',
    },
    relatedTopic: '/study/domain-4/few-shot-prompting',
  },

  // ── Structured Output ─────────────────────────────────────────────────────
  {
    id: 'd4-q5',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A developer needs 100% reliable JSON schema compliance from Claude. They choose between (A) a system prompt instruction "respond with JSON matching this schema" and (B) tool_use with the schema defined in inputSchema. Which is correct?',
    options: {
      A: 'Option A — system prompt is cheaper in tokens',
      B: 'Option B — tool_use enforces the schema at the API protocol level, not just by instruction',
      C: 'Both are equivalent — choose based on preference',
      D: 'Option A — tool_use is only for external service calls',
    },
    correct: 'B',
    explanation: {
      correct: 'tool_use enforces the schema structurally at the API level — types, required fields, and enums are guaranteed by the protocol. System prompt instructions ask Claude to follow the schema but cannot prevent type drift or missing fields. For "100% reliable," tool_use is the correct choice. tool_use is not limited to external service calls — it is the canonical mechanism for structured output extraction.',
      A: 'Token cost is irrelevant when reliability is the requirement.',
      B: 'Correct — tool_use = structural enforcement; system prompt = advisory guidance.',
      C: 'They are not equivalent. tool_use provides schema enforcement; instructions do not.',
      D: 'tool_use is used for structured output extraction, not just external API calls.',
    },
    relatedTopic: '/study/domain-4/structured-output',
  },
  {
    id: 'd4-q6',
    domain: 4,
    scenario: 'payments-api',
    question: 'A developer sets `tool_choice={"type": "auto"}` for data extraction. Sometimes Claude responds in prose instead of calling the tool. What is the fix?',
    options: {
      A: 'Add more few-shot examples of tool calls',
      B: 'Switch to `tool_choice={"type": "any"}` to require a tool call on every response',
      C: 'Increase max_tokens to give Claude room to call the tool',
      D: 'Add "always use the extraction tool" to the system prompt',
    },
    correct: 'B',
    explanation: {
      correct: '`tool_choice: "auto"` lets Claude decide whether to call a tool or respond in prose. For extraction pipelines that always need structured output, `tool_choice: "any"` requires Claude to call one of the provided tools on every response — prose is not allowed. This is the correct lever for enforcing tool use.',
      A: 'Few-shot examples guide behavior but do not enforce tool use when auto mode allows prose.',
      B: 'Correct — `"any"` requires a tool call on every turn.',
      C: 'max_tokens is irrelevant to tool call frequency.',
      D: 'System prompt instructions are advisory — tool_choice is the structural control.',
    },
    relatedTopic: '/study/domain-4/structured-output',
  },

  // ── Validation & Retry ────────────────────────────────────────────────────
  {
    id: 'd4-q7',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A pipeline retries on JSON parse failure: `for _ in range(3): response = client.messages.create(messages=original_messages); try: return parse(response)`. Why does this rarely fix the error?',
    options: {
      A: '3 retries is insufficient — use 10',
      B: 'The same input produces similar outputs — Claude repeats the same mistake without error feedback',
      C: 'messages.create() does not support being called in a loop',
      D: 'JSON parse errors cannot be fixed by retrying',
    },
    correct: 'B',
    explanation: {
      correct: 'Claude is near-deterministic for identical inputs. If the first call produced invalid JSON, subsequent identical calls will likely produce the same invalid JSON. The fix is to append both the bad output and the parse error to the conversation before retrying, giving Claude new information to correct its mistake.',
      A: 'More retries on identical input do not help — frequency is not the issue.',
      B: 'Correct — identical input → similar output. Add error feedback before retrying.',
      C: 'messages.create() is callable in a loop — this is valid Python.',
      D: 'JSON parse errors can be fixed by retry — but only when Claude receives error feedback.',
    },
    relatedTopic: '/study/domain-4/validation-retry',
  },
  {
    id: 'd4-q8',
    domain: 4,
    scenario: 'research-assistant',
    question: 'The API returns a 429 Too Many Requests error. What is the correct handling?',
    options: {
      A: 'Extend the conversation with an error message and retry immediately',
      B: 'Switch to Batch API for higher rate limits',
      C: 'Wait with exponential backoff and jitter, then retry the same request',
      D: 'Increase max_tokens — the request was too large',
    },
    correct: 'C',
    explanation: {
      correct: '429 is a rate limit error — the API rejects requests due to traffic volume, not request content. The correct response is exponential backoff with jitter: increasing delays with randomness to avoid thundering-herd. The same request content is retried unchanged. Conversation extension is for validation failures. Batch API has different semantics (async, minutes latency) and is not a real-time fix.',
      A: 'Conversation extension is for output validation failures, not rate limit errors.',
      B: 'Batch API is a workload choice made upfront, not a runtime rate-limit workaround.',
      C: 'Correct — exponential backoff + jitter is the standard retry strategy for 429 errors.',
      D: '429 is about request volume, not request size — max_tokens is irrelevant.',
    },
    relatedTopic: '/study/domain-4/validation-retry',
  },

  // ── Batch API ─────────────────────────────────────────────────────────────
  {
    id: 'd4-q9',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A team processes 50,000 documents nightly and needs results by 6 AM. Results are processed offline — no real-time requirement. Which API pattern is most appropriate?',
    options: {
      A: 'Synchronous API with parallel async calls for speed',
      B: 'Batch API — designed for high-volume offline processing with ~50% cost reduction',
      C: 'Streaming API for real-time progress monitoring',
      D: 'Synchronous API — Batch API only supports up to 1,000 requests',
    },
    correct: 'B',
    explanation: {
      correct: 'The Batch API is purpose-built for high-volume, offline, async workloads with no real-time latency requirement. It offers approximately 50% cost reduction and processes batches within hours. 50,000 nightly documents with a 6 AM deadline and offline processing is the textbook Batch API use case.',
      A: 'Parallel sync calls work but cost twice as much as Batch API for the same workload.',
      B: 'Correct — Batch API + offline + high volume + cost sensitivity = ideal use case.',
      C: 'Streaming is for real-time interactive use, not bulk offline processing.',
      D: 'Batch API supports up to 100,000 requests per batch — 50,000 is within limits.',
    },
    relatedTopic: '/study/domain-4/batch-api',
  },
  {
    id: 'd4-q10',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A Batch API result has `result.type == "errored"`. What does this mean and what should happen?',
    options: {
      A: 'The entire batch failed — resubmit all requests',
      B: 'That specific request failed — log the error and process other results normally',
      C: 'The model was overloaded — wait 10 minutes and retry the full batch',
      D: 'The result expired — the document exceeded the batch size limit',
    },
    correct: 'B',
    explanation: {
      correct: '`errored` is a per-request result type in Batch API — it means only that specific request failed (invalid content, policy violation, etc.), not the entire batch. The correct action is to log the error for that `custom_id` and continue processing other results. Batch-level failures surface as exceptions, not as individual result types.',
      A: 'Errored is per-request, not batch-level. Other requests likely succeeded.',
      B: 'Correct — per-request error, log and continue. Process other successful results.',
      C: 'Model load issues would cause batch-level errors, not per-request `errored` results.',
      D: '`expired` is a separate result type for timeout. `errored` means the request itself was invalid.',
    },
    relatedTopic: '/study/domain-4/batch-api',
  },

  // ── Prompt Caching ────────────────────────────────────────────────────────
  {
    id: 'd4-q11',
    domain: 4,
    scenario: 'customer-support',
    question: 'A developer adds `cache_control: {type: "ephemeral"}` to their 30,000-token system prompt but `usage.cache_read_input_tokens` is always 0. What is the most likely cause?',
    options: {
      A: 'Prompt caching requires a minimum of 100,000 tokens',
      B: 'Dynamic content (timestamps, user IDs) is included in the cached section, making each request unique',
      C: 'The cache_control flag must be at the end of the messages array',
      D: 'Ephemeral caches expire after 1 minute',
    },
    correct: 'B',
    explanation: {
      correct: 'Cache hits only occur when the cached prefix is byte-identical across requests. If any dynamic content (user IDs, timestamps, request-specific data) is included in the cached section, every request produces a different cache key and misses. Fix: move all dynamic content outside the cached section — into the user turn or a non-cached section.',
      A: 'The minimum for caching is 1,024 tokens for most models — not 100,000.',
      B: 'Correct — dynamic content in the cached section produces a unique cache key each time, causing 100% misses.',
      C: 'cache_control can be in the system prompt or messages array — placement at the end is not required.',
      D: 'Cache TTL is 5 minutes (refreshed on each hit), not 1 minute.',
    },
    relatedTopic: '/study/domain-4/prompt-caching',
  },
  {
    id: 'd4-q12',
    domain: 4,
    scenario: 'data-pipeline',
    question: 'A system prompt has: (1) core instructions — 500 tokens, stable; (2) product catalog — 8,000 tokens, updated weekly; (3) current promotions — 200 tokens, updated daily. Where should cache breakpoints go to maximize cache efficiency?',
    options: {
      A: 'After section 3 only — one breakpoint caches everything',
      B: 'After section 1 and after section 2 — two breakpoints matching content stability boundaries',
      C: 'After section 1 only — only the smallest stable section benefits from caching',
      D: 'No caching — the catalog and promotions change too frequently',
    },
    correct: 'B',
    explanation: {
      correct: 'Two breakpoints match the content stability boundaries: (1) after core instructions (500 tokens, never changes — always cache-hit), (2) after the product catalog (8,000 tokens, changes weekly — cached for a week, refreshed once weekly). The daily promotions (200 tokens) change too frequently and are too small to cache cost-effectively. A single breakpoint after section 3 (A) busts the cache daily. No caching (D) misses significant savings on the 8,000-token catalog.',
      A: 'A single breakpoint after section 3 means the cache busts daily when promotions change.',
      B: 'Correct — two breakpoints aligned to stability boundaries maximizes hits for both stable sections.',
      C: 'Only caching section 1 misses the large savings from the 8,000-token catalog.',
      D: 'The catalog changes weekly — caching it saves significant cost over 7 days per cache write.',
    },
    relatedTopic: '/study/domain-4/prompt-caching',
  },
]
