import type { QuizQuestion } from '@/lib/types'

export const domain2Questions: QuizQuestion[] = [
  // ── MCP Fundamentals ─────────────────────────────────────────────────────
  {
    id: 'd2-q1',
    domain: 2,
    scenario: 'devops-agent',
    question: 'An MCP server exposes a `list_deployments` endpoint that reads deployment status from a database. Should this be implemented as a tool, resource, or prompt?',
    options: {
      A: 'Tool — because it queries an external system',
      B: 'Resource — because it is a read-only data fetch with no side effects',
      C: 'Prompt — because it produces formatted text output',
      D: 'Tool — because it requires authentication',
    },
    correct: 'B',
    explanation: {
      correct: 'MCP resources are for read-only data retrieval — they fetch data into context without side effects. `list_deployments` only reads; it never mutates. Resources are the correct primitive here. Tools are for actions that may have side effects (create, update, delete, send). Authentication requirement does not determine whether something is a tool or resource.',
      A: 'Querying an external system does not make something a tool — reads belong to resources.',
      B: 'Correct — read-only data retrieval is the defining characteristic of MCP resources.',
      C: 'Prompts are reusable template definitions, not data fetch operations.',
      D: 'Authentication is an implementation detail, not a classification criterion for MCP primitives.',
    },
    relatedTopic: '/study/domain-2/mcp-fundamentals',
  },
  {
    id: 'd2-q2',
    domain: 2,
    scenario: 'customer-support',
    question: 'An MCP client connects to a server. The server responds to the `initialize` request but never sends `notifications/initialized` back. What stage of the protocol is stuck?',
    options: {
      A: 'Tool discovery — the server has not listed its tools yet',
      B: 'The capability handshake — initialization has not been acknowledged by the client, so neither party should proceed with tool calls',
      C: 'Transport negotiation — stdio vs HTTP has not been resolved',
      D: 'Nothing is stuck — `notifications/initialized` is optional',
    },
    correct: 'B',
    explanation: {
      correct: 'The MCP initialization sequence is: (1) client sends `initialize`, (2) server responds with capabilities, (3) client sends `notifications/initialized` to acknowledge. This third step is sent by the client, not the server. If the client never sends it, the handshake is incomplete and the server should not proceed. The question describes the scenario in reverse — the client must send the notification after receiving the server\'s response.',
      A: 'Tool discovery (`tools/list`) happens after initialization — it cannot be stuck at this stage yet.',
      B: 'Correct — the handshake requires all three messages to complete before either party proceeds.',
      C: 'Transport is established before the initialize message is sent.',
      D: '`notifications/initialized` is required by the protocol, not optional.',
    },
    relatedTopic: '/study/domain-2/mcp-fundamentals',
  },

  // ── Tool Descriptions ─────────────────────────────────────────────────────
  {
    id: 'd2-q3',
    domain: 2,
    scenario: 'payments-api',
    question: 'A tool description reads: `"charge_card": "Charges a credit card."` Claude calls this tool in scenarios where it should only verify card validity, causing unintended charges. What is the fix?',
    options: {
      A: 'Rename the tool to `verify_and_charge_card` for clarity',
      B: 'Rewrite the description to specify: when to use it, that it DOES initiate a real charge, and that verification-only operations should use `verify_card` instead',
      C: 'Add `"never call this tool"` to the system prompt',
      D: 'Remove the tool from the server and require direct API calls instead',
    },
    correct: 'B',
    explanation: {
      correct: 'The description "Charges a credit card" is ambiguous — Claude cannot tell whether to use it for verification or charging. A good description must specify: the exact action taken (real charge, not verification), when to call vs. when not to call, and how it relates to similar tools. Explicit negative guidance ("do not use for validation-only scenarios") is part of a complete tool description.',
      A: 'Renaming without improving the description does not clarify behavior.',
      B: 'Correct — tool descriptions must specify what the tool does, when to use it, and when NOT to use it (especially for high-stakes operations).',
      C: 'A system prompt instruction is advisory — better tool descriptions are more targeted and reliable.',
      D: 'Removing the tool is unnecessarily drastic — the description is the issue, not the tool\'s existence.',
    },
    relatedTopic: '/study/domain-2/tool-descriptions',
  },
  {
    id: 'd2-q4',
    domain: 2,
    scenario: 'data-pipeline',
    question: 'A developer is designing tools for a data processing agent. They create 8 tools that mirror the REST API endpoints 1:1: `get_user`, `get_user_orders`, `get_order`, `get_order_items`, etc. What is wrong with this design?',
    options: {
      A: 'MCP tools must be named with snake_case, which these are not',
      B: 'Too granular — answering common agent tasks requires chaining many tool calls, increasing latency and error surface',
      C: 'REST endpoint mirroring is correct — it ensures consistency between the MCP server and the API',
      D: 'Agents can only use up to 5 tools — this design has too many',
    },
    correct: 'B',
    explanation: {
      correct: 'MCP tools should be designed around agent tasks, not data model CRUD operations. If answering "show me a user\'s recent orders with items" requires 4 separate tool calls (get_user → get_user_orders → get_order → get_order_items), that\'s 4x the latency, 4x the error surface, and 4x the cost. Task-oriented tools like `get_user_with_recent_orders` serve the agent\'s actual needs in one call.',
      A: 'snake_case is a convention, not a requirement — it has no bearing on this architectural issue.',
      B: 'Correct — tool granularity should match agent task granularity, not API endpoint granularity.',
      C: 'REST endpoints are designed for human developers and generic clients. MCP tools should be designed for the agent\'s specific tasks.',
      D: 'There is no 5-tool limit in MCP.',
    },
    relatedTopic: '/study/domain-2/tool-descriptions',
  },

  // ── MCP Servers ───────────────────────────────────────────────────────────
  {
    id: 'd2-q5',
    domain: 2,
    scenario: 'research-assistant',
    question: 'A Python MCP server uses `requests.get()` inside an `async def call_tool()` handler. During load testing, all concurrent requests stall when one slow API call is in-flight. What is wrong?',
    options: {
      A: 'MCP servers cannot handle concurrent requests by design',
      B: '`requests.get()` is synchronous blocking I/O — it blocks the event loop, stalling all other async handlers',
      C: 'The `@app.call_tool()` decorator does not support async functions',
      D: 'The server needs more worker processes to handle concurrency',
    },
    correct: 'B',
    explanation: {
      correct: 'MCP Python servers run on an async event loop. Calling synchronous blocking I/O (`requests.get()`) inside an `async def` handler blocks the event loop entirely — no other coroutines can run until the blocking call returns. The fix is to use an async HTTP client (`httpx.AsyncClient`) with `await` so the event loop can handle other requests while waiting for the HTTP response.',
      A: 'MCP servers fully support concurrent requests — that\'s a core feature of async architecture.',
      B: 'Correct — `requests` is blocking; use `httpx` with `await` for async-compatible HTTP calls.',
      C: '`@app.call_tool()` fully supports async handler functions.',
      D: 'More processes would not fix the problem — the issue is blocking within a single async handler.',
    },
    relatedTopic: '/study/domain-2/mcp-servers',
  },
  {
    id: 'd2-q6',
    domain: 2,
    scenario: 'devops-agent',
    question: 'An MCP tool handler receives an unknown tool name. Which is the correct error handling approach?',
    options: {
      A: 'Return an empty TextContent with isError=False so the agent can continue',
      B: 'Raise a Python exception — unknown tool names are protocol-level errors',
      C: 'Return TextContent with isError=True and the error message',
      D: 'Log the error and return None',
    },
    correct: 'B',
    explanation: {
      correct: 'MCP defines two error modes: (1) Protocol errors — malformed requests, unknown tool names — should raise exceptions. (2) Content errors — expected runtime failures like "file not found" or "rate limited" — should return content with isError=True. An unknown tool name is a protocol-level problem (the client requested something that doesn\'t exist) and should be an exception.',
      A: 'Returning success for an unknown tool masks the error and confuses the client.',
      B: 'Correct — unknown tool = protocol error = raise exception.',
      C: 'isError=True is for expected content errors (not-found, timeout, permission denied), not for protocol violations.',
      D: 'Returning None breaks the protocol — the server must return a valid response or raise an exception.',
    },
    relatedTopic: '/study/domain-2/mcp-servers',
  },

  // ── MCP Clients ───────────────────────────────────────────────────────────
  {
    id: 'd2-q7',
    domain: 2,
    scenario: 'code-review',
    question: 'An MCP client calls `tools/list` and receives a list of 15 tools. The developer hardcodes the tool schemas in their application rather than using the discovered list. A week later, the server adds 3 new tools. What happens?',
    options: {
      A: 'The client automatically discovers the new tools on the next connection',
      B: 'The new tools are unavailable to the client until the hardcoded list is manually updated',
      C: 'The server sends a push notification to the client about the new tools',
      D: 'Claude automatically detects and uses the new tools through model knowledge',
    },
    correct: 'B',
    explanation: {
      correct: 'One of MCP\'s key advantages is dynamic tool discovery via `tools/list` — servers can add tools without requiring client changes. But if the client hardcodes the schema instead of using the discovered list, it loses this benefit. The new tools are invisible to the client until someone manually adds them. The correct pattern is to call `tools/list` at connection time and use the server-provided schemas.',
      A: 'Discovery only happens when `tools/list` is called — and if schemas are hardcoded, they won\'t use the discovered list anyway.',
      B: 'Correct — hardcoding schemas defeats dynamic discovery. The new tools are invisible to the client.',
      C: 'MCP uses `listChanged` notifications to signal when tool lists change, but the client must still call `tools/list` to fetch the updates.',
      D: 'Claude\'s tool knowledge comes from schemas provided at request time, not from model training.',
    },
    relatedTopic: '/study/domain-2/mcp-clients',
  },

  // ── Tool Scoping ──────────────────────────────────────────────────────────
  {
    id: 'd2-q8',
    domain: 2,
    scenario: 'customer-support',
    question: 'A customer support agent has access to tools: `lookup_order`, `issue_refund`, `delete_account`, `update_billing`. A customer asks about their order status. Which tools should be available for this interaction?',
    options: {
      A: 'All four tools — the agent may need any of them depending on how the conversation evolves',
      B: 'Only `lookup_order` — provide only the tools needed for the current task context',
      C: '`lookup_order` and `issue_refund` — order lookups often lead to refund requests',
      D: 'None — customer support agents should not have tool access',
    },
    correct: 'B',
    explanation: {
      correct: 'Tool scoping is the practice of providing only the tools needed for the current task. For an order status inquiry, `lookup_order` is sufficient. Including `delete_account` and `update_billing` creates unnecessary risk — a mis-fired tool call or prompt injection could trigger destructive actions that are entirely irrelevant to the user\'s question.',
      A: 'Providing all tools "in case they\'re needed" maximizes blast radius. Scope tools to the minimum required.',
      B: 'Correct — minimal tool access for the current task context. `lookup_order` is all that\'s needed here.',
      C: 'Speculative tool inclusion (the agent "might" need it) is how unnecessary risk accumulates.',
      D: 'Tools are the mechanism by which agents take useful actions — removing all tools eliminates the agent\'s capability.',
    },
    relatedTopic: '/study/domain-2/tool-scoping',
  },
  {
    id: 'd2-q9',
    domain: 2,
    scenario: 'data-pipeline',
    question: 'A data pipeline agent is in "read-only audit mode." How should tool scoping be applied?',
    options: {
      A: 'Provide all tools but add "do not write anything" to the system prompt',
      B: 'Remove all write/mutating tools from the available tool set and provide only read tools',
      C: 'Provide all tools and rely on the model\'s judgment to avoid writes in audit mode',
      D: 'Disable tool use entirely and have the agent reason only from provided data',
    },
    correct: 'B',
    explanation: {
      correct: 'If the mode is read-only, the enforcement must be structural: remove all write/mutating tools from the tool list. The model cannot accidentally or maliciously call a tool that is not present. System prompt instructions are advisory — if write tools are available, the model may call them despite instructions. Tool scoping is the code-level equivalent of "principle of least privilege."',
      A: 'Advisory instructions + available write tools = the model can still call them. Structural removal is required.',
      B: 'Correct — structural removal of write tools is the only reliable enforcement of read-only mode.',
      C: 'Relying on model judgment for safety-critical constraints is an anti-pattern.',
      D: 'Disabling all tools is unnecessarily restrictive — read tools are still useful for audit.',
    },
    relatedTopic: '/study/domain-2/tool-scoping',
  },

  // ── Structured Errors ─────────────────────────────────────────────────────
  {
    id: 'd2-q10',
    domain: 2,
    scenario: 'payments-api',
    question: 'A payment tool handler encounters a database timeout when processing a charge. The charge may or may not have been committed. What is the correct response?',
    options: {
      A: 'Raise a Python exception — timeouts are protocol errors',
      B: 'Return TextContent with isError=True, include the error type ("timeout"), state of the charge (unknown/possibly committed), and suggest using the idempotency key to check status',
      C: 'Return success with isError=False — the charge may have gone through',
      D: 'Silently retry the charge immediately to ensure it completes',
    },
    correct: 'B',
    explanation: {
      correct: 'A database timeout is an expected operational failure (not a protocol error), so it should return content with isError=True. Critically, it must include: the error type, the ambiguous state of the charge (committed or not), and actionable guidance (use the idempotency key to check). This gives the orchestrating agent enough information to decide whether to retry safely.',
      A: 'Timeouts are expected content errors, not protocol violations — use isError=True, not exceptions.',
      B: 'Correct — expected failures use isError=True with structured context including charge state and recovery guidance.',
      C: 'Returning success when the operation may have failed is a silent failure — the worst possible outcome for a payment.',
      D: 'Silently retrying a potentially-committed charge can cause a double charge.',
    },
    relatedTopic: '/study/domain-2/structured-errors',
  },
  {
    id: 'd2-q11',
    domain: 2,
    scenario: 'code-review',
    question: 'A tool handler wraps its entire body in a bare `except Exception: return []`. What is the problem with this pattern?',
    options: {
      A: 'Returning an empty list is not a valid MCP response type',
      B: 'Swallowing all exceptions as empty results causes silent failure — the caller cannot distinguish "no results" from "an error occurred"',
      C: 'Exception handlers must log errors before returning',
      D: 'The handler should re-raise the exception for the MCP framework to handle',
    },
    correct: 'B',
    explanation: {
      correct: 'Returning `[]` on any exception is a silent failure pattern. The calling agent sees an empty list and interprets it as "zero results found" — it cannot detect that an error occurred. This is especially dangerous for search/lookup tools where empty results are a valid success state. The fix is to return a structured error response (isError=True with error details) so the caller can distinguish failure from empty success.',
      A: 'Returning an empty list is technically valid MCP syntax but semantically wrong in this pattern.',
      B: 'Correct — silent failure conflates error with empty success. Always signal errors explicitly.',
      C: 'Logging is good practice but does not fix the silent failure problem for the caller.',
      D: 'Re-raising for protocol errors is correct, but content errors should return structured error content.',
    },
    relatedTopic: '/study/domain-2/structured-errors',
  },
  {
    id: 'd2-q12',
    domain: 2,
    scenario: 'research-assistant',
    question: 'After a successful MCP tool call, the response has `isError: false` but the `content[0].text` contains `{"error": "rate_limited", "retry_after": 30}`. How should the MCP client handle this?',
    options: {
      A: 'Treat it as a success — isError=false means the call succeeded',
      B: 'Ignore isError and always parse the text content for embedded error signals',
      C: 'The client should inspect content for embedded error signals when designing the tool contract — the server is using a content-level error pattern',
      D: 'This is a malformed response — isError must be true for any error condition',
    },
    correct: 'C',
    explanation: {
      correct: 'Some servers embed error information in the text content even with isError=false — this is an application-level error pattern rather than the MCP protocol error flag. When designing the tool contract, both client and server must agree on how errors are signaled. The client should parse the JSON content and check for error fields. Ideally, the server should set isError=true for this scenario, but if the tool contract defines embedded errors, the client must handle them.',
      A: 'isError=false with embedded error content means the application layer has its own error convention — treat it according to the tool contract.',
      B: 'Always ignoring isError defeats the purpose of the protocol flag — use both isError and content parsing according to the agreed contract.',
      C: 'Correct — tool contracts must define how errors are signaled. If the server uses embedded errors, the client must parse them.',
      D: 'isError=true is the protocol-correct way, but servers may deviate — clients must handle both patterns defensively.',
    },
    relatedTopic: '/study/domain-2/structured-errors',
  },
]
