import type { QuizQuestion } from '@/lib/types'

export const domain3Questions: QuizQuestion[] = [
  // ── CLAUDE.md Hierarchy ───────────────────────────────────────────────────
  {
    id: 'd3-q1',
    domain: 3,
    scenario: 'code-review',
    question: 'A team has: `~/.claude/CLAUDE.md` (global), `./CLAUDE.md` (project root), and `./src/payments/CLAUDE.md` (subdirectory). A developer runs Claude Code from the `./src/payments/` directory. Which files are loaded?',
    options: {
      A: 'Only `./src/payments/CLAUDE.md` — the most specific file wins',
      B: 'Only `./CLAUDE.md` — the project root is the canonical source',
      C: 'All three files are loaded and concatenated — global first, project second, subdirectory last',
      D: '`~/.claude/CLAUDE.md` and `./src/payments/CLAUDE.md` — skipping the project root',
    },
    correct: 'C',
    explanation: {
      correct: 'Claude Code loads all three CLAUDE.md levels and concatenates them — they do not override each other. The load order is: global first, project root second, subdirectory last. All three sets of instructions are active simultaneously. This is addition, not override: subdirectory context adds to project context, which adds to global context.',
      A: 'CLAUDE.md files are not "most specific wins" — all levels are loaded and combined.',
      B: 'The project root is not the only source — all levels are loaded.',
      C: 'Correct — all three levels are loaded and concatenated in order: global → project → subdirectory.',
      D: 'The project root CLAUDE.md is not skipped — it is always part of the loaded context.',
    },
    relatedTopic: '/study/domain-3/claude-md-hierarchy',
  },
  {
    id: 'd3-q2',
    domain: 3,
    scenario: 'devops-agent',
    question: 'A CLAUDE.md file contains `@docs/deployment-runbook.md`. What does this do when Claude Code loads the file?',
    options: {
      A: 'Creates a link to the file that Claude can click during the session',
      B: 'Inlines the content of `docs/deployment-runbook.md` into the CLAUDE.md context at that position',
      C: 'Instructs Claude to read the file when explicitly asked about deployment',
      D: 'Triggers a git fetch to ensure the referenced file is up to date',
    },
    correct: 'B',
    explanation: {
      correct: 'The `@path/to/file` syntax in CLAUDE.md is an import directive — the referenced file\'s content is inlined at that position when CLAUDE.md is loaded. This is resolved at session start, not on demand. The imported content becomes part of Claude\'s context as if it had been written directly in CLAUDE.md.',
      A: 'There is no clickable link mechanism in CLAUDE.md imports.',
      B: 'Correct — `@file` inlines the file content at load time. It is not a reference or lazy load.',
      C: 'Imports are resolved eagerly at session start, not on-demand when a topic is mentioned.',
      D: 'CLAUDE.md imports do not trigger any git operations.',
    },
    relatedTopic: '/study/domain-3/claude-md-hierarchy',
  },

  // ── Slash Commands ─────────────────────────────────────────────────────────
  {
    id: 'd3-q3',
    domain: 3,
    scenario: 'code-review',
    question: 'A developer creates `.claude/commands/audit.md` with the content: `Run a security audit of: $ARGUMENTS`. They invoke it with `/audit src/auth/`. What text is sent as the user message?',
    options: {
      A: '`Run a security audit of: $ARGUMENTS`  — variables are not expanded in command files',
      B: '`Run a security audit of: src/auth/` — $ARGUMENTS is replaced with everything after the command name',
      C: '`Run a security audit of: ` — $ARGUMENTS expands to empty if no quotes are used',
      D: 'The command fails — $ARGUMENTS requires double-dollar syntax `$$ARGUMENTS`',
    },
    correct: 'B',
    explanation: {
      correct: '`$ARGUMENTS` is substituted with everything typed after the command name when the command is invoked. So `/audit src/auth/` sends "Run a security audit of: src/auth/" as the user message. The substitution captures everything after the command name as a single string.',
      A: '$ARGUMENTS is a valid placeholder that is expanded at invocation time.',
      B: 'Correct — $ARGUMENTS is replaced with the full text after the command name: "src/auth/".',
      C: '$ARGUMENTS captures everything after the command name including unquoted paths.',
      D: 'The correct syntax is `$ARGUMENTS` (single dollar, no double syntax required).',
    },
    relatedTopic: '/study/domain-3/slash-commands',
  },
  {
    id: 'd3-q4',
    domain: 3,
    scenario: 'devops-agent',
    question: 'A team wants to share a `/deploy-checklist` command with all developers. Where should the command file be stored?',
    options: {
      A: '`~/.claude/commands/deploy-checklist.md` — global user commands',
      B: '`.claude/commands/deploy-checklist.md` in the project repo — committed to git',
      C: '`CLAUDE.md` — commands must be embedded in the CLAUDE.md file',
      D: '`src/.claude/commands/deploy-checklist.md` — commands go in the source directory',
    },
    correct: 'B',
    explanation: {
      correct: 'Project-level slash commands live in `.claude/commands/` at the project root and are committed to git. When a team member clones the repo, they automatically get all project commands. User-level commands in `~/.claude/commands/` are personal and not shared. There is no embedding mechanism in CLAUDE.md for commands.',
      A: 'User-level commands (`~/.claude/commands/`) are personal shortcuts — not shared with the team.',
      B: 'Correct — `.claude/commands/` in the repo root, committed to git, shares commands across the whole team.',
      C: 'CLAUDE.md contains context and conventions, not slash command definitions.',
      D: 'Commands are not placed in `src/` — they go in `.claude/commands/` at the project root.',
    },
    relatedTopic: '/study/domain-3/slash-commands',
  },

  // ── Agent Skills ──────────────────────────────────────────────────────────
  {
    id: 'd3-q5',
    domain: 3,
    scenario: 'code-review',
    question: 'What is the functional difference between a slash command file and a skill file, both stored in `.claude/commands/`?',
    options: {
      A: 'Slash commands are for read-only tasks; skills can write files',
      B: 'Skills include trigger conditions that allow them to auto-activate; slash commands are always manually invoked',
      C: 'Skills require a separate `skills.json` manifest; slash commands are self-contained',
      D: 'There is no difference — skills and slash commands are identical',
    },
    correct: 'B',
    explanation: {
      correct: 'Both are stored as `.md` files in `.claude/commands/`, but skills include structured trigger condition descriptions — natural language that tells Claude when to automatically activate the skill based on user input. A slash command without trigger conditions must always be manually invoked with `/command-name`. The distinction is manual vs. potentially auto-triggered invocation.',
      A: 'Read/write capability is determined by tool permissions, not command vs. skill classification.',
      B: 'Correct — skills have trigger conditions enabling auto-activation; slash commands are always manual.',
      C: 'There is no `skills.json` manifest — both are plain `.md` files in the same directory.',
      D: 'The trigger condition metadata is the key structural difference.',
    },
    relatedTopic: '/study/domain-3/agent-skills',
  },
  {
    id: 'd3-q6',
    domain: 3,
    scenario: 'payments-api',
    question: 'A skill file begins with: `"Use this skill when the user pastes a stack trace, error message, or describes a crash."` A developer types "why is my login failing?" without a stack trace. Should the skill activate?',
    options: {
      A: 'Yes — "login failing" implies a crash, which matches the trigger',
      B: 'No — the trigger requires a literal stack trace or error message to be present',
      C: 'Depends — Claude evaluates the trigger condition against the actual user input and decides',
      D: 'Yes — all skills activate for any question about software problems',
    },
    correct: 'C',
    explanation: {
      correct: 'Trigger conditions are natural language evaluated by Claude against the actual user message. "Why is my login failing?" describes a problem but does not include a stack trace or error message. Claude would likely not activate this skill because the trigger specifically asks for a pasted error or description of a crash — not a generic question. The interpretation is probabilistic and context-dependent.',
      A: '"Login failing" is a question, not a crash description with error details — the trigger likely would not match.',
      B: 'The trigger says "describes a crash" which could match, but the phrasing here is more of a general question.',
      C: 'Correct — Claude evaluates the natural language trigger against the message. This is a judgment call.',
      D: 'Skills do not blanket-activate for any software problem — trigger conditions narrow the activation scope.',
    },
    relatedTopic: '/study/domain-3/agent-skills',
  },

  // ── Plan Mode ─────────────────────────────────────────────────────────────
  {
    id: 'd3-q7',
    domain: 3,
    scenario: 'devops-agent',
    question: 'A developer activates Plan Mode and asks Claude to "outline the changes needed to migrate our CI/CD pipeline from CircleCI to GitHub Actions." During Plan Mode, which operations can Claude perform?',
    options: {
      A: 'Only text generation — Claude cannot use any tools in Plan Mode',
      B: 'Read files and search the codebase — but not write files or run shell commands',
      C: 'All operations except git push',
      D: 'No operations — Plan Mode is purely a display mode showing the user\'s plan',
    },
    correct: 'B',
    explanation: {
      correct: 'Plan Mode blocks side-effecting operations (file writes, shell commands, API calls) while allowing read-only operations. Claude can read the existing CircleCI config files, grep the codebase for CircleCI-specific patterns, and explore the directory structure — all read-only. This is how Claude builds the plan: by exploring the actual codebase. It just cannot make changes while doing so.',
      A: 'Read tools are allowed in Plan Mode — exploration is necessary to build an accurate plan.',
      B: 'Correct — read-only tools are available; write and execute tools are blocked.',
      C: 'File writes and arbitrary shell commands are blocked, not just git push.',
      D: 'Plan Mode is an active state where Claude explores the codebase — not a passive display mode.',
    },
    relatedTopic: '/study/domain-3/plan-mode',
  },
  {
    id: 'd3-q8',
    domain: 3,
    scenario: 'code-review',
    question: 'How do you toggle Plan Mode in Claude Code?',
    options: {
      A: 'Type `/plan` in the prompt',
      B: 'Press `Shift + Tab`',
      C: 'Set `CLAUDE_PLAN_MODE=true` in the environment',
      D: 'Press `Ctrl + P`',
    },
    correct: 'B',
    explanation: {
      correct: '`Shift + Tab` toggles Plan Mode on and off in Claude Code. Pressing it once enters Plan Mode (Claude explores and plans but does not execute); pressing it again exits Plan Mode and Claude can proceed with execution.',
      A: '`/plan` is not a built-in slash command for Plan Mode — the keyboard shortcut is the toggle mechanism.',
      B: 'Correct — `Shift + Tab` toggles Plan Mode.',
      C: 'There is no `CLAUDE_PLAN_MODE` environment variable for toggling Plan Mode.',
      D: '`Ctrl + P` is not the Plan Mode shortcut.',
    },
    relatedTopic: '/study/domain-3/plan-mode',
  },

  // ── CI/CD Integration ─────────────────────────────────────────────────────
  {
    id: 'd3-q9',
    domain: 3,
    scenario: 'devops-agent',
    question: 'A GitHub Actions workflow needs Claude Code to review a PR diff and output JSON that a downstream step can parse. Which command is correct?',
    options: {
      A: '`claude "review this PR" --json`',
      B: '`claude -p "review this PR diff" --output-format json`',
      C: '`claude --non-interactive --format=json "review this PR diff"`',
      D: '`claude run --output json "review this PR diff"`',
    },
    correct: 'B',
    explanation: {
      correct: 'The correct flags are `-p` (non-interactive, print mode) and `--output-format json`. `-p` runs Claude Code with a single prompt and exits — required for CI where no keyboard is available. `--output-format json` serializes the complete response as a JSON object with `result`, `cost_usd`, `duration_ms`, and other metadata for downstream parsing.',
      A: '`--json` is not a valid Claude Code flag.',
      B: 'Correct — `-p` for non-interactive mode, `--output-format json` for structured output.',
      C: '`--non-interactive` and `--format=json` are not valid Claude Code flags.',
      D: '`claude run` is not valid syntax — the command is `claude` with `-p` for non-interactive.',
    },
    relatedTopic: '/study/domain-3/ci-cd-integration',
  },
  {
    id: 'd3-q10',
    domain: 3,
    scenario: 'code-review',
    question: 'A CI job runs `claude -p "fix all ESLint errors in src/"` without specifying `--allowedTools`. What is the risk?',
    options: {
      A: 'No risk — Claude Code defaults to read-only mode in CI',
      B: 'Claude has access to all tools by default, including arbitrary shell execution — a misinterpreted prompt could run destructive commands',
      C: 'The command will fail — `--allowedTools` is required for CI usage',
      D: 'Claude will ask for tool permission interactively, blocking the CI job',
    },
    correct: 'B',
    explanation: {
      correct: 'Without `--allowedTools`, Claude Code has access to all available tools including `Bash` for shell execution. In CI, there is no human to reject unexpected tool calls. If Claude misinterprets the task or is given a maliciously crafted codebase, it could run shell commands beyond the intended fix. The principle of least privilege applies: grant only the tools needed (`Read`, `Edit`, `Glob`, `Grep` for an ESLint fix).',
      A: 'Claude Code does not default to read-only — all tools are available unless restricted.',
      B: 'Correct — full tool access in headless CI is a blast radius risk. Always scope with `--allowedTools`.',
      C: '`--allowedTools` is optional but strongly recommended — omitting it does not cause a failure.',
      D: 'In non-interactive mode (`-p`), Claude does not prompt for permission — it uses what\'s available.',
    },
    relatedTopic: '/study/domain-3/ci-cd-integration',
  },

  // ── MCP Configuration ──────────────────────────────────────────────────────
  {
    id: 'd3-q11',
    domain: 3,
    scenario: 'data-pipeline',
    question: 'A `.mcp.json` file contains: `{"mcpServers": {"db": {"command": "node", "args": ["./db-mcp.js"], "env": {"DB_PASSWORD": "prod-secret-123"}}}}`. What is wrong with this configuration?',
    options: {
      A: 'The `command` field should be `"npx"` not `"node"`',
      B: 'The DB_PASSWORD is hardcoded — it will be committed to git and exposed to anyone with repo access',
      C: 'The `args` array should not include relative paths',
      D: '`env` is not a valid field in `.mcp.json` server configurations',
    },
    correct: 'B',
    explanation: {
      correct: '`.mcp.json` is committed to version control. Hardcoding secrets (passwords, API keys, tokens) in this file exposes them to everyone with repository access, including in git history even after deletion. The fix is to use `${ENV_VAR}` syntax: `"DB_PASSWORD": "${DB_PASSWORD}"` — the actual value comes from the shell environment or CI secrets management and never touches the file.',
      A: '`node` is a valid command — the choice between `node` and `npx` depends on the project setup.',
      B: 'Correct — secrets must never be hardcoded in `.mcp.json`. Use `${ENV_VAR}` references.',
      C: 'Relative paths in `args` are valid — they resolve relative to the `cwd` or working directory.',
      D: '`env` is a valid and commonly used field in MCP server configuration.',
    },
    relatedTopic: '/study/domain-3/mcp-config',
  },
  {
    id: 'd3-q12',
    domain: 3,
    scenario: 'code-review',
    question: 'A developer wants to add a personal GitHub MCP server that works in all their projects, without sharing it with teammates. Where should this be configured?',
    options: {
      A: '`.mcp.json` at the project root — it will be gitignored automatically',
      B: '`~/.claude/settings.json` under the `mcpServers` key',
      C: '`CLAUDE.md` in the home directory with MCP server details',
      D: 'Each project\'s `.claude/commands/` directory',
    },
    correct: 'B',
    explanation: {
      correct: 'User-level MCP server configuration lives in `~/.claude/settings.json` under `mcpServers`. This file is personal — not shared via git — and the configured servers are available in all projects. Project-level servers go in `.mcp.json` at the repo root (and are committed to git). The developer wants personal-only, so the user settings file is correct.',
      A: '`.mcp.json` is committed to git by default — it is not gitignored automatically.',
      B: 'Correct — `~/.claude/settings.json` with `mcpServers` is the user-level, personal, all-projects location.',
      C: 'CLAUDE.md contains guidance text, not MCP server definitions.',
      D: '`.claude/commands/` is for slash commands and skills, not MCP server configuration.',
    },
    relatedTopic: '/study/domain-3/mcp-config',
  },
]
